name: Update proto

on:
  schedule:
    - cron: "*/5 * * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Git setup
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github@s.k-kachi.net"
        git config --global push.default current
        git remote set-url origin https://gkkachi:${GITHUB_TOKEN}@github.com/gkkachi/firestore-grpc.git
        git checkout -b master
    - name: Cargo setup
      run: |
        rustup update
        cargo login ${CRATES_IO_TOKEN}
        cargo install cargo-bump
    - name: Update proto
      run: bash update.sh
    - name: Commit proto
      run: git add . && git commit -m "Update proto"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Bump version
      run: cargo-bump minor --git-tag
    - name: Commit new version
      run: git add . && git commit -m "New version"
    - name: Git push
      run: git push
    - name: publish
      run: cargo publish
